spring:
  datasource:
    username: record_label
    password: record_label
    url: jdbc:mysql://localhost:3306/record_label
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
 